services:
  - type: web
    name: zefron-tube
    env: static
    buildCommand: npm install -g pnpm && pnpm install --frozen-lockfile && pnpm --filter @workspace/zefron-tube run build
    staticPublishPath: artifacts/zefron-tube/dist
    envVars:
      - key: BASE_PATH
        value: /
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
